services:
  api:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/news_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/code/app

  db:
    image: postgres:18.3-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d news_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: