services:
  api:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: sh -c "cd /code/app && alembic upgrade head && cd /code && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /code/app"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@dev_db:5432/news_db
      - CRAWLER_INTERVAL_SECONDS=300
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SENDER=no-reply@newsradar.local
      - SMTP_USE_TLS=false
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - ./backend:/code
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/health || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 1s
      start_interval: 0s

  dev_db:
    image: postgres:18.3-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d news_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
      start_interval: 0s

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./frontend:/code
      - frontend_node_modules:/code/node_modules

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"


volumes:
  postgres_data:
  frontend_node_modules:
