"""Add source_id column to Alert table

Revision ID: 88ee65cd8148
Revises: c0ef8833917d
Create Date: 2026-04-16 21:16:28.190522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ee65cd8148'
down_revision: Union[str, Sequence[str], None] = 'c0ef8833917d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_source_id'), 'alerts', ['source_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_source_id'), table_name='alerts')
    op.drop_column('alerts', 'source_id')
    # ### end Alembic commands ###
