"""Set on delete cascade option on source_id foreign key in news table

Revision ID: c0ef8833917d
Revises: e9b068e3a326
Create Date: 2026-04-14 21:03:40.262878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ef8833917d'
down_revision: Union[str, Sequence[str], None] = 'e9b068e3a326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('news_source_id_fkey'), 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(op.f('news_source_id_fkey'), 'news', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###
