"""add new fields to alerts

Revision ID: e9b068e3a326
Revises: 7515cb2144f0
Create Date: 2026-04-10 23:22:49.874260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b068e3a326'
down_revision: Union[str, Sequence[str], None] = '7515cb2144f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column(
        "alerts",
        sa.Column("expanded_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("alerts", sa.Column("category", sa.String(length=255), nullable=True))
    op.add_column(
        "alerts",
        sa.Column("notify_in_app", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    op.add_column(
        "alerts",
        sa.Column("notify_email", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )

    op.execute("UPDATE alerts SET name = keyword WHERE name IS NULL")
    op.execute("UPDATE alerts SET expanded_keywords = '[]'::jsonb WHERE expanded_keywords IS NULL")
    op.execute("UPDATE alerts SET category = 'general' WHERE category IS NULL")

    op.alter_column("alerts", "name", nullable=False)
    op.alter_column("alerts", "expanded_keywords", nullable=False)
    op.alter_column("alerts", "category", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "notify_email")
    op.drop_column("alerts", "notify_in_app")
    op.drop_column("alerts", "category")
    op.drop_column("alerts", "expanded_keywords")
    op.drop_column("alerts", "name")
    # ### end Alembic commands ###
