"""add_cron_expression_to_alerts

Revision ID: efcce35ef89a
Revises: e623709a0305
Create Date: 2026-04-24 10:49:18.554429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcce35ef89a'
down_revision: Union[str, Sequence[str], None] = 'e623709a0305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column(
            "cron_expression",
            sa.String(length=100),
            nullable=False,
            server_default="*/5 * * * *",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'cron_expression')
    # ### end Alembic commands ###
